name: "HAVNC-DRAGONS"
description: "VNC straight to your dashboard - here be dragons version (also known as bleeding edge, might not work)"
version: "0.1.1"
slug: "havnc-dragons"
init: false
full_access: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080
options:
  url: "http://homeassistant:8123"
  resolution: "768x1024"
  password: null
  persist_data: false 
schema:
  url: "str"
  resolution: "str"
  password: "password"
  persist_data: "bool"
image: "ghcr.io/gnyman/{arch}-havnc-dragons"
