[program:Chromium]
command=bash -c 'if [ "$(jq --raw-output ".persist_data // true" /data/options.json)" = "true" ]; then CHROME_DIR="/data/chrome-data"; else CHROME_DIR="/tmp/chrome-data"; fi && mkdir -p "$CHROME_DIR" && touch "$CHROME_DIR/First Run" && chromium --guest --kiosk --no-sandbox --test-type --no-first-run --disable-dev-shm-usage --start-maximized --noerrdialogs --user-data-dir="$CHROME_DIR" $(jq --raw-output ".url // \"http://homeassistant:8123\"" /data/options.json)'
priority=5
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
